// An array of info for pages

var pages = [{
    color: "#4dc48a",
    title: "Traditional Economy",
    img: "media/traditional-economy.PNG",
    desc: "Much like a bartering system, a <mark>Traditional Economy</mark> operates on direct production and distribution. This economy also weighs heavily on cultural and economic beliefs. There's not usually a surplus of products, as these economies tend to only make what they need. A <mark>Traditional Economy</mark> is usually the first form of economy in a country, and it usually evolves into another economy as it grows over time.",
    q1: "This economy focuses heavily on raw materials from hunting & gathering.",
    q2: "Through gathering, hunting, or preparing by hand. Goods are not produced in the most efficient way, but rather by traditional methods that are a part of a society's culture.",
    q3: "For the close knit culture/community the members of the economy live in, usually not for larger societies.",
    positive: ["Everyone knows their role", "Cultural and religious traditions dictate the market, so little disagreements", "More sustainable than technology-based economies", "Small and more environmentally-conscious"],
    negative: ["The economy is subject to weather and environmental changes", "Vulnerable to the control of other stronger market and/or command economies"],
    example: " Bhutan is a developing country, so they use a <mark>Traditional Economy</mark>, but this country is growing, so their economy will also change with their progress. Their economy specializes in hydropower, thanks to their plentiful rivers and other waterways. Despite this modern trade, they rely on their own cultural traditions. A little over half of their employment is in agricultural jobs (54%) even though this industry only makes up about 10% of their Gross Domestic Product. This industry is linked to poverty, as 2/3rds of those who are in poverty in Bhutan work agricultural jobs. This country is closely tied to India, one of their neighboring countries and major trading partners for hydropower. In turn India also provides them aid, as Bhutan is susceptible to natural disasters due to its geographical location. India also provides 80% of Bhutan's imports, which mainly consist of fuels, metals, and machinery.",
    gdp: "",
    life_expectancy: "",
    literacy_rate: "",
    poverty_rate: "",
    labor_rate: "",
    unemployment_rate: "",
    military_spending: "",
    major_industry: "",
    imports: "",
    exports: ""
}, {
    color: "#4287f5",
    title: "Market Economy",
    img: "media/market-economy.png",
    desc: "<mark>Market Economies</mark> are heavily controlled by supply and demand. For this, businesses sell to the highest price people are willing to pay for their product, while people look for the lowest price to buy products they want. Workers and employers also have some of the same characteristics in this economy, as both wish to profit the most. Capitalism, which is heavy on the characteristics of supply and demand, requires a market economy to operate on changing prices over time.",
    q1: "In this economy, natural resources, capital, and labor are the main trades.",
    q2: "By the most efficient way possible. This economy encourages people to find more efficient ways to beat out competition, such as using automation.",
    q3: "Those that consider the high price put out by sellers to be the lowest price on the market. Goods and services are open to everyone to buy, but only those who are willing to pay the price.",
    positive: ["The most desired good are produced often (thanks to supply and demand)", "Goods are produced in more efficient ways", "New products can be made by anyone & added into the economy"],
    negative: ["The market is a competition (people can be at a disadvantage financially, politically, etc)", "Not everyone is taken care of", "Some are forced to work menial jobs to support their family rather than receiving a higher education"],
    example: "Hong Kong operates under an open <mark>Market Economy</mark>. Under this economy, everyone's private property is protected by law. People are allowed to own and open their own businesses. Labor codes are enforced, but only to keep everyone safe, and they aren't too invasive or controlling. Trade taxes and other tariffs are kept low to encourage everyone to trade. The government only has control of the cost of residential rent, so almost all prices aren't controlled by the government. Because of its open market, Hong Kong invests and trades globally. China is Hong Kong's biggest trading partner, as in 2008 they exported 48.5% of goods and imported 46.6% of goods with China. Hong Kong mainly imports raw materials and semi-manufactured goods, mainly exporting electrical machinery and other appliances. ",
    gdp: "",
    life_expectancy: "",
    literacy_rate: "",
    poverty_rate: "",
    labor_rate: "",
    unemployment_rate: "",
    military_spending: "",
    major_industry: "",
    imports: "",
    exports: ""
}, {
    color: "#e3a740",
    title: "Command Economy",
    img: "media/command-economy.PNG",
    desc: "A <mark>Command Economy</mark> is controlled by the government. They make all economic decisions for the country, including allocating resources and deciding what goods should be produced, according to their own central plan. This economy is much more controlled, but that also means that it doesn't allow for much freedom.",
    q1: "The government decides what goods and services to add to their economy.",
    q2: "The government decides when, how, and how many goods should be produced. People are hired according to the government's hiring targets & other regulations they enforce.",
    q3: "The government distributes goods however they see fit, according to their own plan.",
    positive: ["Have access to all of the country's resources without lawsuits or environmental regulatory issues", "Society can be transformed to fit the eyes of the government and their plan"],
    negative: ["The government and/or rapid change can ignore the people's wants & needs encouraging the creation of a black market that goes against the government's regulations", "Production doesn't usually fit the demand for a good", "Poor planning can lead to rationing", "Innovation and entrepreneurship are discouraged so less new products are created", "Production might not grow more efficiently without the motivation of competition", "People are rewarded for following orders & staying in line instead of following their desires"],
    example: "Belarus operates under a <mark>Command Economy</mark>. In this economy prices are controlled by the government, so this limits how much profit companies can make and what goods can be sold. This economy is a remnant of the Soviet republic, and it has yet to be liberated to a different type of economy. Because of this, Belarus has some of the worst human rights records in all of Europe. Currently the government is in charge of about 70 percent of the economy. Due to this high amount of control the government has over the economy, their government is highly susceptible to corruption, as they have no accountability in place for what the government does. This control also severely limits the investment opportunities everyone in Belarus has. Belarus mainly imports crude petroleum and exports refined petroleum. ",
    gdp: "",
    life_expectancy: "",
    literacy_rate: "",
    poverty_rate: "",
    labor_rate: "",
    unemployment_rate: "",
    military_spending: "",
    major_industry: "",
    imports: "",
    exports: ""
}, {
    color: "#7a1e8f",
    title: "Mixed Economy",
    img: "media/mixed-economy.png",
    desc: "A <mark>Mixed Economy</mark> is an economy that combines characteristics from other economies, such as those from <mark>traditional</mark>, <mark>market</mark>, and <mark>command</mark> economies. From a <mark>Market Economy</mark>, it protects private property, is a free market, and is driven by the wants of people. From a <mark>Command Economy</mark>, the government is in charge of the larger parts of the economy, such as safeguards, international trade, and the military. Depending on what the people want, the government has control over certain industries, like health care, retirement, and banking. From a <mark>Traditional Economy</mark>, people retain traditions passed down from generation to generation, like fishing and hunting, but these traditions are no longer big enough to direct the economy. From globalization, most countries are, to some degree, a <mark>Mixed Economy</mark>.",
    q1: "Similar to a <mark>Market Economy</mark>, natural resources, crafted goods, luxury goods, capital, and labor are all available. ",
    q2: "Like a <mark>Market Economy</mark>, goods and services are produced in the most efficient way possible, and these methods of production grow more efficient through competition.",
    q3: "Similar to a <mark>Market Economy</mark>, the market is dictated by supply and demand, so goods and services are open to everyone to buy, but only those who are willing to pay the price set by the buyer.",
    positive: ["Distributes goods to who needs them first", "Encourages the most efficient production methods and most popular goods with high profits", "Encourages the innovation of new products and methods", "Minimizes the disadvantages of a <mark>Market Economy</mark>"],
    negative: ["Is still susceptible to the disadvantages of a <mark>Traditional Economy</mark>, <mark>Market Economy</mark>, and <mark>Command Economy</mark>", "Too much freedom within the market can lead to smaller businesses being left unsupported by the government", "Government could still spend too much on the industries they are allowed control over", "Government could favor big businesses and give them more tax breaks that are unfair to all other businesses"],
    example: "The United States operates under a <mark>Mixed Economy</mark>. In this economy, people are free to buy and sell goods and services on the market without government control. This generates a lot of customer spending, which makes up about 70% of the total Gross Domestic Product of the United States. But to balance this out, the government has control over the military and some small areas of other industries, showing its characteristics of a <mark>Command Economy</mark>. Despite the freedom in the market, the Pew Research Center found that only 18% of Americans trusted the government in 2017. Also in 2017, the United States was the 3rd largest exporter in the world, exporting about $1.25 Trillion dollars in a variety of products, including refined petroleum and a variety of vehicles. The United States was the 1st largest importer in the world in 2017, importing about $2.16 trillion dollars in a variety of products, including cars, crude oil, and a variety of appliances. This also shows that people in the United States are consumers, as the monetary value of imports was almost twice as much as the monetary value of exports.",
    gdp: "",
    life_expectancy: "",
    literacy_rate: "",
    poverty_rate: "",
    labor_rate: "",
    unemployment_rate: "",
    military_spending: "",
    major_industry: "",
    imports: "",
    exports: ""
}]

var lastPageInfo = {
    title: "Choice System",
    desc: [
        "I believe that a <mark>Mixed Economy</mark> is the best economy. This type of economy has a mix of the characteristics of a <mark>Traditional Economy</mark>, <mark>Market Economy</mark>, and a <mark>Command Economy</mark>. This makes it so that the economy is still a free market, so anyone can sell goods at their own chosen price. This also means that anyone can buy any goods within the market with little restriction, as long as they are willing to pay the chosen price. Because of this freedom, <mark>Mixed Economies</mark> are still driven by the laws of supply and demand, where the wants of the people direct the products produced in the economy. This could also be because I live in the United States, a country that uses a <mark>Mixed Economy</mark>, so I prefer what I know and what I was raised in."],
    citations: [
        'Amadeo, Kimberly. "Command Economy, Its Characteristics, Pros, and Cons." The Balance, Dotdash, 7 Dec. 2019, www.thebalance.com/command-economy-characteristics-pros-cons-and-examples-3305585.',
        'Amadeo, Kimberly. "Market Economy, Its Characteristics, Pros, and Cons, with Examples." The Balance, Dotdash, 4 Mar. 2020, www.thebalance.com/market-economy-characteristics-examples-pros-cons-3305586.',
        'Amadeo, Kimberly. "Mixed Economy With Pros, Cons, and Examples." The Balance, Dotdash, 11 Feb. 2020, www.thebalance.com/mixed-economy-definition-pros-cons-examples-3305594.',
        'Amadeo, Kimberly. "Traditional Economy With Its Characteristics, Pros, Cons, and Examples." The Balance, Dotdash, 11 Mar. 2020, www.thebalance.com/traditional-economy-definition-examples-pros-cons-3305587.',
        'Amadeo, Kimberly. "US Economy Fast Facts and Summary." The Balance, Dotdash, 6 Mar. 2020, www.thebalance.com/us-economy-facts-4067797.',
        '"Belarus." 2019 Index Of Economic Freedom, The Heritage Foundation, 2019, www.heritage.org/index/country/belarus.',
        'Guichard, Aurelien. "United States." OEC, The Observatory of Economic Complexity, 2017, oec.world/en/profile/country/usa/.',
        'Hadzinski, Paval. "Belarus." OEC, The Observatory of Economic Complexity, 2017, oec.world/en/profile/country/blr/.',
        '"Hong Kong Trade, Exports and Imports." Economy Watch: Follow The Money, Economywatch.com, 15 Mar. 2010, www.economywatch.com/world_economy/hong-kong/export-import.html.',
        '"Hong Kong." 2019 Index Of Economic Freedom, The Heritage Foundation, 2019, www.heritage.org/index/country/hongkong.',
        '"United States." 2019 Index Of Economic Freedom, The Heritage Foundation, 2019, www.heritage.org/index/country/unitedstates.',
        '"The World Bank In Bhutan." World Bank, World Bank Group, 17 Oct. 2019, www.worldbank.org/en/country/bhutan/overview.'
    ]
}